version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - MODEL_PATH=${MODEL_PATH}
      - S3_PREFIX=${S3_PREFIX}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    privileged: true
